
languageCode = 'en-us'
title = "Test blog"
theme = "hugo-PaperMod"
sectionPagesMenu = "main"
enableRobotsTXT = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20

[taxonomies]
  tag = 'tags'

